### PR TITLE
chore: add Dev Valecha as finallist winner.

### PR DESCRIPTION
**Pull request by iamdevvalecha**
screenshot:-
Screenshot from 2021-06-27 16-06-57

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
@mariobehling

**Comment by pc-beast** [comment]
Your image height looks larger than normal. It may create uneven layout. Please see what is wrong with the classes you used.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please change the image to one that has the same height and width.

**Comment by mariobehling** [comment]
Please update the screenshot and resolve conflicts.

**Comment by iamdevvalecha** [comment]
need to close this pr.

**Pull request closed without merging**
