### PR TITLE
Added Dark mode Support

### PR DESCRIPTION
**Pull request by Abhijay007**

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
Plz add the screenshot and issue number in pr description.

**Comment by Abhijay007** [comment]
> Plz add the screenshot and issue number in pr description.


> Plz add the screenshot and issue number in pr description.

@Raunaksingh100  sir, there is no issue related to this but I think it is an important feature that's why I implemented this, can I raise this issue on my own? 


here is the video in a gif format:
codeheat

**Comment by arnoob16** [comment]
> here is the video in a gif format:
> codeheat

@Abhijay007 In the dark mode, the texts aren't that clearly visible. I think you can work on that to improve your PR.

**Comment by Abhijay007** [comment]
> > here is the video in a gif format:
> > codeheat
> 
> @Abhijay007 In the dark mode, the texts aren't that clearly visible. I think you can work on that to improve your PR.

@arnoob16 sir, this is a compressed GIF video that's why I think the text part is not that clearly visible. I suggest you to run the code manually once, That may be visible clearly.

**Comment by Raunaksingh100** [comment]
@Abhijay007 you can also  provide the deploy link for this

**Comment by Abhijay007** [comment]
> @Abhijay007 you can also provide the deploy link for this

https://elastic-sinoussi-c5cf64.netlify.app/ 

@Raunaksingh100 Sir this is a netlify deployed link so images(codeheat banner image) may not be visible that good but you can see that on the above gif a well.

**Comment by mariobehling** [comment]
no need for dark mode. Please rather contribute to our software projects. Thanks.

**Pull request closed without merging**
