### PR TITLE
feat: Add website generator to projects

### LINKED ISSUE #207: Add website generator to projects
Website generator is not listed yet.

### PR DESCRIPTION
**Pull request by HeroicHitesh**
Fixes #207 

Screenshot 2020-09-28 at 10 42 52 PM

### CODE REVIEW

**Comment by HeroicHitesh** [comment]
@mariobehling @shivaylamba @ShridharGoel @liveHarshit @uds5501 @kushthedude Please have a look into the PR and let me know if further modifications are required.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Seems like you stretched the image vertically. So, it is distorted.

**Comment by HeroicHitesh** [comment]
@mariobehling Updated the image as well as the ss of website after the change in the PR description

**Review by Raunaksingh100 — COMMENTED** [review]
plz resolve the conflicts

**Comment by HeroicHitesh** [comment]
> plz resolve the conflicts in index.html file

Merge conflicts Resolved
@Raunaksingh100 @mariobehling

**Comment by mariobehling** [comment]
Thank you for your contribution. Would be great if you could help with our actual software projects and participate in the codeheat contest. All codeheat eligible issues are here: https://github.com/search?l=&o=desc&q=org%3Afossasia+org%3Avoicerepublic+label%3Acodeheat+state%3Aopen&s=created&type=Issues

**Comment by HeroicHitesh** [comment]
> Thank you for your contribution. Would be great if you could help with our actual software projects and participate in the codeheat contest. All codeheat eligible issues are here: https://github.com/search?l=&o=desc&q=org%3Afossasia+org%3Avoicerepublic+label%3Acodeheat+state%3Aopen&s=created&type=Issues

Sure, commented on an [issue](https://github.com/fossasia/open-event-frontend/issues/5260) in Open Event Frontend

**Pull request merged**
