### PR TITLE
Add Vibhor Verma's image

### PR DESCRIPTION
**Pull request by vibhcool**
This PR Adds Vibhor Verma's image and details

### CODE REVIEW

**Comment by harshit98** [comment]
@vibhcool You can crop your image. That trick will do the work. Don't change the CSS code. :)

**Comment by vibhcool** [comment]
@harshit98 @mariobehling , I have fixed the issue, please see :)

**Comment by mariobehling** [comment]
The image is too big. Should not be bigger than 30KB and 300x300. Thanks.

**Comment by vibhcool** [comment]
@mariobehling, please re-review, I have fixed the size

**Pull request merged**
