### PR TITLE
Add Prateek as Mentor

### PR DESCRIPTION
**Pull request by prateekj117**

### CODE REVIEW

**Comment by prateekj117** [comment]
@iamareebjamal @mariobehling Ready for review.

**Review by iamareebjamal — APPROVED** [review]

**Comment by mariobehling** [comment]
Sorry, there was another PR from Hong Phuc. Please resolve conflicts. Thanks.

**Comment by prateekj117** [comment]
After updating:

Screenshot from 2020-10-04 21-55-57

@iamareebjamal @mariobehling Ready for another review.

**Review by vsasvipul0605 — APPROVED** [review]

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
