### PR TITLE
Fix: Remove Codeheat 2019 from about section #210 

### LINKED ISSUE #210: Remove Codeheat 2019 from about section
URL is not opening from about section: https://2019.codeheat.org/

### PR DESCRIPTION
**Pull request by asha15**
Fixed #210 

Screenshot (289)

### CODE REVIEW

**Comment by asha15** [comment]
@liveHarshit preview link to index.html page : https://htmlpreview.github.io/?https://github.com/asha15/codeheat.org/blob/gh-pages/index.html

**Comment by asha15** [comment]
@liveHarshit  Sir can i know do this merge will be count for the final result of CodeHeat?

**Comment by liveHarshit** [comment]
> @liveHarshit Sir can i know do this merge will be count for the final result of CodeHeat?

Every contribution will count. Try to do better contributions in active projects.
Thank you.

**Comment by asha15** [comment]
@liveHarshit ok sir, Thank you for the reply :)

**Pull request merged**
