### PR TITLE
Solved navbar content overlap in mobile review issue #244

### PR DESCRIPTION
**Pull request by 26Vinayak**
in Reference to issue #244 

Ongoing through the code, it seems like overlap nav bar content in mobile review in screen size 970px - 991px. I am taking a look alongside to try to fix it.

in this meanwhile, i am pushing this change.

WhatsApp Image 2020-10-01 at 10 41 39 AM

Now it seems to be correct.

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
can you provide the deploy link

**Review by Raunaksingh100 — CHANGES_REQUESTED** [review]
you can close this pull request you delete the whole files of this website

**Review by ayushontop — COMMENTED** [review]
Somes files are deleted , You should close the pr

**Comment by Raunaksingh100** [comment]
@26Vinayak you can close this pr

**Pull request closed without merging**
