### PR TITLE
feat: Add Duc Le - codeheat mentor

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes: #197

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@anhanh11001 Resolve conflicts

**Comment by mrsaicharan1** [comment]
Why was this even merged? The image size should've been 300x300. Fix this.

**Comment by shreyanshdwivedi** [comment]
@anhanh11001 maybe you can update the PR description too and add a screenshot of the change. This will help us to review quickly

**Comment by liveHarshit** [comment]
@mrsaicharan1 @shreyanshdwivedi Ratio is 1:1 How are you calculating?

**Comment by liveHarshit** [comment]
@anhanh11001 Please send a PR to resize the image, it's not exact 1:1.

**Comment by anhanh11001** [comment]
Yes, I'm in the lecture, will do it later today

**Pull request merged**
