### PR TITLE
Fix: Image responsiveness issue in mobile view

### PR DESCRIPTION
**Pull request by anilmaurya61**
Capture2

### CODE REVIEW

**Comment by anilmaurya61** [comment]
> Please resolve merge conflicts.

Done!

**Comment by anilmaurya61** [comment]
> Please resolve merge conflicts.

I have opened new PR

https://github.com/fossasia/codeheat.org/pull/270

**Review by Raunaksingh100 — COMMENTED** [review]
Plz squash your commits...

**Comment by mariobehling** [comment]
This is working as expected. No changes are needed.

**Pull request closed without merging**
