### PR TITLE
Saumya Chitransh as finalist winner

### LINKED ISSUE #295: Create a section for winners of Codeheat Period 1
Please create a section for winners of Codeheat 1 above the section "Jury" as follows:
* Add two areas with a) heading Grand Winners and b) Finalist winners
* Add three winners with headshot color images below each heading
* Add profile links for scroll over and names below winners
* Ensure profile links are centered correctly

### PR DESCRIPTION
**Pull request by Saumyachitransh01**
fixes #295 

Screenshot from 2020-12-21 18-27-33

### CODE REVIEW

**Review by Raunaksingh100 — APPROVED** [review]

**Review by sachinchauhan2889 — COMMENTED** [review]
your name is not there in finalist winner list.
winners codeheat

**Comment by Saumyachitransh01** [comment]
> ## your name is not there in finalist winner list.
> winners codeheat

It was a confusion. I did got the email

**Comment by Saumyachitransh01** [comment]
> ## your name is not there in finalist winner list.
> winners codeheat

It was a confusion in  announcing the names between Soumi and Saumya. 
I got the email too.

**Comment by Saumyachitransh01** [comment]
Screenshot_2020-12-22-13-18-49-39

**Comment by mariobehling** [comment]
Please change image to a head shot, e.g. similar to Shubham.

**Comment by Saumyachitransh01** [comment]
> Please change image to a head shot, e.g. similar to Shubham.

Please check now @mariobehling

**Comment by Raunaksingh100** [comment]
> > Please change image to a head shot, e.g. similar to Shubham.
> 
> Please check now @mariobehling  

Plz update your screenshot in or description

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
