### PR TITLE
[docs] structured and update the readme.md file 

### PR DESCRIPTION
**Pull request by An-prog-hub**

### CODE REVIEW

**Comment by An-prog-hub** [comment]
Anyone from this organization please review !!!!!!

**Review by Raunaksingh100 — COMMENTED** [review]
No need of this you can close this pr

**Comment by An-prog-hub** [comment]
@rctay @Raunaksingh100  @smcgregor  @Orbiter Please review !!!!!

**Comment by Raunaksingh100** [comment]
> @rctay @Raunaksingh100  @smcgregor  @Orbiter Please review !!!!!

No need of this plz close your pr thanks

**Comment by Raunaksingh100** [comment]
Plz work on fossaisa project issues

**Pull request closed without merging**
