### PR TITLE
Fix Navbar Responsive

### PR DESCRIPTION
**Pull request by Manish-Kumarr**
Fix Navbar issue #244 

Changed -> @media all and (**max-width: 968px**)  to  @media all and (**max-width: 992px**)

Note: All the extra changes occur due to my default VS Code editor setting like (double quote to single and space)

### CODE REVIEW

**Comment by Manish-Kumarr** [comment]
@Raunaksingh100 https://codeheat.imfast.io

**Comment by mariobehling** [comment]
Seems a good change, however all these extra changes cannot be accepted. Please only provide changes that take care of the issue.

**Review by vsasvipul0605 — APPROVED** [review]

**Comment by Manish-Kumarr** [comment]
> Seems a good change, however all these extra changes cannot be accepted. Please only provide changes that take care of the issue. 

@mariobehling  fine

**Comment by Raunaksingh100** [comment]
The issue is now closed so you can closed this pr .

**Comment by Raunaksingh100** [comment]
fixed -
https://github.com/fossasia/codeheat.org/pull/281

**Pull request closed without merging**
