### PR TITLE
fix: aligmnet of the back to top button

### PR DESCRIPTION
**Pull request by Raunaksingh100**
### Description--
Fix alignment of the back to top button in the mobile view see in the screenshot for the better understanding..

### issue-
#253 

### screenshot before-
before

### screenshot after--
after

@mariobehling plz review

### CODE REVIEW

**Review by cggvuhh — APPROVED** [review]
Good work!!

**Comment by HeroicHitesh** [comment]
@Raunaksingh100 I think it's already solved in #260 So, this PR can be closed.

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 I think it's already solved in #260 So, this PR can be closed.

The pr is not good I fixed this properly see the requested changes and the pr is still pending from one month

**Comment by HeroicHitesh** [comment]
> > @Raunaksingh100 I think it's already solved in #260 So, this PR can be closed.
> 
> The pr is not good I fixed this properly see the requested changes on that prs and the pr is still pending from one month
> 
> And the pr maker is also not active from one month

@mariobehling can have a look at the 2 PRs and decide which one to move forward with. 
But IMO, the first one should be merged. There's just an empty line change requested there which is good-to-have but not a required change.
Also, the PR review and merge process are pretty slow, making people inactive in the org. Maybe we need more active reviewers and people with write access in FOSSASIA.

**Comment by mariobehling** [comment]
This is a minor issue that does not impact the usage of the site. There are many minor issues on websites. These could become a priority if they impact the usage of a site. Maintainers would mark those issues as "high priority". If issues on website are not a high priority they might not get reviewed in a quick manner. FOSSASIA maintainers usually focus on software projects rather than on our websites. Also with the software projects - projects have different priorities. Some projects are used by more people and have full time developers. Other projects are community-led and devs contribute only in their free time. In any case we recommend people to focus contributions on software projects rather than websites. Thank you and keep it up!

**Pull request closed without merging**
