### PR TITLE
Added finalist winner Shubham Upreti(progmatic99)

### LINKED ISSUE #295: Create a section for winners of Codeheat Period 1
Please create a section for winners of Codeheat 1 above the section "Jury" as follows:
* Add two areas with a) heading Grand Winners and b) Finalist winners
* Add three winners with headshot color images below each heading
* Add profile links for scroll over and names below winners
* Ensure profile links are centered correctly

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #295 

Screenshot from 2020-12-15 12-51-06

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
Why unnecessary changes

**Comment by progmatic-99** [comment]
Which changes are you talking about?

**Comment by Raunaksingh100** [comment]
@progmatic-99 can you tell me what is the need of svg file 

see this pr #299

**Comment by cggvuhh** [comment]
@progmatic-99 why you added svg file you can upload your photo from your computer

see this or #299

**Pull request merged**
