### PR TITLE
Add Afzal as Finalist Winner

### PR DESCRIPTION
**Pull request by afzal442**
Added Afzal as Finalist Winner

### CODE REVIEW

**Comment by iamareebjamal** [comment]
It's empty file

**Comment by afzal442** [comment]
@iamareebjamal sir, have a look

**Comment by iamareebjamal** [comment]
Still empty

**Comment by afzal442** [comment]
sir, could you tell me why that file is showing empty when I have added my photo?

**Comment by iamareebjamal** [comment]
Must be a bug in github

**Pull request merged**
