### PR TITLE
Fixed Mentor Images scaling problem

### PR DESCRIPTION
**Pull request by sandmanx**
Fixed the issue #11 by adding a css class, background-image in custom.css and linking it to the index.html file.
Also fixed the problem with hovercard by forcibly fixing its width at 300px.

Before:
rsz_screenshot_from_2016-09-23_01-24-09

rsz_screenshot_from_2016-09-23_01-24-58

rsz_screenshot_from_2016-09-23_01-25-09

After:
rsz_screenshot_from_2016-09-23_04-10-48

rsz_screenshot_from_2016-09-23_04-11-01

rsz_screenshot_from_2016-09-23_04-11-07

### CODE REVIEW

**Comment by the-dagger** [comment]
Looks good, thanks!

**Comment by mariobehling** [comment]
I am confused where this bug came from and when it appeared. This worked in all my versions and I never encountered it.

**Comment by the-dagger** [comment]
@mariobehling I can confirm this issue happening with me on chrome.

**Comment by mariobehling** [comment]
Where does sulphur-css come from? This site is getting incompatible with Bootstrap.

**Comment by mariobehling** [comment]
Ok, thanks. Cleaned up some files just now. It was originally ok on Chrome/Fx. Not sure where this happened. Thanks.

**Comment by sandmanx** [comment]
@mariobehling Even though my commit has been merged, the images are still not scaling properly on decreasing the browser width. I fixed kind of same issue in http://2016.fossasia.org/ . You see the bug is caused due to a mistake while making the site. Each image has a background-image class assigned to it, but there is no such class. Taking cue from https://github.com/fossasia/2016.fossasia.org/commit/d99c3f9fc882b8cced0a6aecf8af36e516238a61 I linked the custom.css in the index.html file and created the background-image class. This fixed the issue. So should I create another PR, because the issue is still present?

**Comment by mariobehling** [comment]
Yes, please. Thank you!

**Comment by sandmanx** [comment]
@mariobehling Fixed it in PR #15 . Cheers!

**Pull request merged**
