### PR TITLE
Center Align the speaker info on mobile screens

### LINKED ISSUE #64: Positioning of speaker info on mobile screens
The speaker info including the image and the name floats left. It looks very odd and would be better if it is center aligned.

### PR DESCRIPTION
**Pull request by parimatrix**
@mariobehling Fixes #64 by preventing float left of the contents.

### CODE REVIEW

**Comment by isuruAb** [comment]
@mariobehling  do we need this feature. @parimatrix  it is better if you can provide a preview link for this.

**Comment by parimatrix** [comment]
@isuruAb Yes sir, it's quite a minor edit. But I think it is kind of needed. I am attaching the screenshots.
Current version: 

screenshot 12
Center Aligned: 

screenshot 13

**Comment by isuruAb** [comment]
@parimatrix  can you upload screenshots in different screen sizes.

**Comment by parimatrix** [comment]
You can review the changes on this link 
https://parimatrix.github.io/codeheat.org/

Thanks

**Comment by parimatrix** [comment]
@isuruAb Sir, I added the media-query, second part solved. But for some reason, the first background image issue only appears on GitHub pages. I cannot figure out the reason for that.

**Comment by isuruAb** [comment]
@parimatrix rebase your working branch and check again

**Comment by parimatrix** [comment]
@isuruAb Sir, I confirm it's a Github pages issue. I completely erased my earlier forked repo, forked again and just tested on Github pages without any changes. The issue of the background image remains. Will soon submit a new PR from the new forked repo.

**Pull request closed without merging**
