### PR TITLE
Fixes #107: Added Grand Prize Winners and Finalist Winner

### LINKED ISSUE #107: Add Grand Prize Winners and Finalist Winners
Please add two sections similar to https://2016.codeheat.org/#winners for Grand Prize Winners and Finalist Winners and include images and links.

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #107 

**Tool used to find social account: [StalkPy](https://github.com/vaibhavsingh97/StalkPy)**

Live link: https://vaibhavsingh97.github.io/codeheat.org/

Cc: @gabru-md @ParthS007 @jajodiaraghav @anshumanv @agbilotia1998 @ms10398 @nikit19 @ritikamotwani
Please do check your details and also, please comment below to change your Picture, add social media links, etc.
Also, Do check @mariobehling comment and give me your photos. Just comment with the update photo

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks, but please find photos that only show the winner and no-one else on the photo. Also try to find photos that show the face of the person in large. Cheers.

**Comment by nikit19** [comment]
@vaibhavsingh97 Can you please add my linkedIn and twitter too?
https://www.linkedin.com/in/nikit-bhandari/
https://twitter.com/NikitBhandari
Thank you

**Comment by jajodiaraghav** [comment]
Please add my Linkedin profile link as well https://www.linkedin.com/in/jajodiaraghav/

**Comment by ParthS007** [comment]
@vaibhavsingh97  Thanks, Please remove Reddit link and add Linked Profile [https://www.linkedin.com/in/parth-shandilya-b6aaa9138/](https://www.linkedin.com/in/parth-shandilya-b6aaa9138/) and Facebook profile [https://www.facebook.com/shandilyaparth](https://www.facebook.com/shandilyaparth)

**Comment by vaibhavsingh97** [comment]
Added requested changes 👍

**Comment by ritikamotwani** [comment]
@vaibhavsingh97 Thank you, but can you change my twitter profile link to: https://twitter.com/Ritika_Motwani and add my linkedin profile:  https://www.linkedin.com/in/ritika-motwani-47b770131/

**Comment by gabru-md** [comment]
@vaibhavsingh97 please wait. I'll pe providing with a link to my image. As Mario said, It should preferably show the face.
And will be putting up links to my profiles as well

**Comment by gabru-md** [comment]
My LinkedIn link : [https://www.linkedin.com/in/manish-devgan-468179137](https://www.linkedin.com/in/manish-devgan-468179137)
My Twitter Link : [https://twitter.com/gabru_md](https://twitter.com/gabru_md)

Solo Image : [Imgur Link](https://i.imgur.com/Tm6KL3C.jpg)

**Comment by anshumanv** [comment]
@vaibhavsingh97 
My linkedin - https://www.linkedin.com/in/anshumanv12/
Image - https://postimg.org/image/k3kos6b8l/

**Comment by mariobehling** [comment]
Hey guys, I am merging this as work in progress. Please make a pull request to improve this. Specifically avoid pictures with other people. 

Instead of posting comments here, a simple way to update a pull request is simply to make a pull request to the branch of the developer and updating the PR. This would mean we are really implementing a distributed workflow. Cheers.

**Pull request merged**
