### PR TITLE
Fixes #105 Modify the image for query-server project

### LINKED ISSUE #105: Modify the image for query-server project
**Current Behavior**
query-one

**Expected Behavior**
query-2

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #105 

**Before Change**

query-one

**After Change**

query-2

@hpdang @mariobehling @jigyasa-grover Please review . Thanks !!

### CODE REVIEW

**Comment by mariobehling** [comment]
It is unclear to me, what is the problem. Therefore closing it.

**Comment by bhaveshAn** [comment]
@mariobehling Earlier we had the image where the buttons were used in the UI for the respective search engine and now the `query-server` is having dropdown menu for the search  engines and also the radio buttons for `General`, `Image` and `Video`.

Let me know can you figure out the issue now.

**Comment by mariobehling** [comment]
Imagine 5 people review this and everyone takes 15 minutes to check email, read the comments and the code. All together 1.15h would be spent on this PR that is simply a change of a picture on a website that is only relevant for a few months. Please avoid such PRs and discussions on this.

**Comment by bhaveshAn** [comment]
Sure :-1:

**Pull request closed without merging**
