### PR TITLE
fix(ui): removed extra white space on mobile devices

### PR DESCRIPTION
**Pull request by faisaljamil25**
fix(ui): Removed extra white space on mobile devices( #329 )

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
plz add the before and after screenshot in your pr description.

**Comment by faisaljamil25** [comment]
Before

Screenshot 2021-03-01 005246

After

Screenshot 2021-03-01 201819

There is a white space at the right side of the screen that stretches down to the bottom on screens of width less than 780px which can be removed by adding `overflow-x: hidden;` to the div.

**Comment by faisaljamil25** [comment]
@Raunaksingh100 I have shared the screenshots as you have suggested. Let me know if any further changes needed.

**Review by EricLiclair — APPROVED** [review]

**Comment by Ubayed-Bin-Sufian** [comment]
Fixes #329

**Pull request merged**
