### PR TITLE
Add Kush to Grand Winners:

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

/cc @mariobehling

### CODE REVIEW

**Comment by kushthedude** [comment]
http://highfalutin-donkey.surge.sh

**Comment by kushthedude** [comment]
@mariobehling Please merge!

**Comment by mariobehling** [comment]
Please resolve conflicts. Thanks.

**Comment by kushthedude** [comment]
> Please resolve conflicts. Thanks.

Done @mariobehling

**Pull request merged**
