### PR TITLE
Adding Padmal to mentors' list

### PR DESCRIPTION
**Pull request by CloudyPadmal**

### CODE REVIEW

**Comment by isuruAb** [comment]
@CloudyPadmal  please resolve conflicts

**Comment by CloudyPadmal** [comment]
Hi @isuruAb ! I've resolved them! :)

**Comment by isuruAb** [comment]
@CloudyPadmal  but your face is not properly visible in your profile picture.

**Comment by CloudyPadmal** [comment]
Hi @isuruAb ! I've replaced the image with a new one! :)

**Comment by CloudyPadmal** [comment]
Thanks @isuruAb !

**Pull request merged**
